server:
  port: 8091

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
    properties:
      hibernate:
        type: trace
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Postgres settings
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
